apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
      app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pgrep telegraf && pgrep nginx
          initialDelaySeconds: 20
          periodSeconds: 10
---
apiVersion: v1
kind: Service	
metadata:
  name: nginx-service
  annotations:
    metallb.universe.tf/allow-shared-ip: svc
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    name: http
    targetPort: 80
  - protocol: TCP
    port: 443
    name: https
    targetPort: 443