apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: 
      app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx-image
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service	
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: hello-blue-whale-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080